sonar.organization=thorsten-klein
sonar.projectKey=thorsten-klein_venv-patcher

sonar.sources=venv_patcher
sonar.tests=tests
sonar.python.version=3.9,3.10,3.11,3.12,3.13

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml
